name: Deploy to GitHub Pages

on:
  push:
    branches:
      - fresh-gh-pages-test  # もしくは main/master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # GitHub が自動で用意するトークン
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # ビルド成果物のパス
          publish_dir: ./dist
          # デプロイ先ブランチ
          publish_branch: gh-pages
