name: Deploy to GitHub Pages

# GitHub Token にページ公開の書き込み権限を付与
permissions:
  pages: write
  contents: read

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # デフォルトの GITHUB_TOKEN ではなく PAT を使って checkout
          token: ${{ secrets.GH_PAGES_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # ここも PAT
          github_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist
          # optional: コミット作者情報
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
