name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (use PAT & disable default creds)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAGES_TOKEN }}    # ← PAT を指定
          persist-credentials: false              # ← デフォルト creds をOFF
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN }}   # ← 同じPATを使ってpush
          publish_branch: gh-pages
          publish_dir: ./dist
          commit_user_name: "github-actions[bot]"
          commit_user_email: "41898282+github-actions[bot]@users.noreply.github.com"
