name: Build & Deploy to GitHub Pages

# main への push をトリガーに動作
on:
  push:
    branches:
      - main

permissions:
  contents: read   # コードをチェックアウトする権限
  pages: write     # GitHub Pages を更新する権限

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) ソースコード取得
      - uses: actions/checkout@v3

      # 2) Node.js 環境セットアップ
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 3) 依存インストール＆ビルド
      - run: |
          npm ci
          npm run build

      # 4) ビルド成果物をアップロード（v2 を指定！）
      - name: Upload artifacts for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist

      # 5) GitHub Pages にデプロイ
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
