# .github/workflows/pages.yml
name: Deploy to GitHub Pages via gh-pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: List dist folder
        run: ls -R dist

      - name: Configure Git user for gh-pages
        run: |
          git config --global user.name  "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Deploy to gh-pages
        env:
          GH_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
        run: |
          npx gh-pages \
            --dist dist \
            --branch gh-pages \
            --dotfiles
