name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read   # ソースチェックアウト
  pages:   write   # Pages 更新

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # --- checkout (PAT を使う) ---
      - uses: actions/checkout@v3
        with:
          persist-credentials: false      # デフォルト GITHUB_TOKEN を無効化
          token:            ${{ secrets.GH_PAGES_TOKEN }}
          fetch-depth:      0

      # --- Node.js & ビルド ---
      - uses: actions/setup-node@v3
        with: { node-version: '16' }

      - run: |
          npm ci
          npm run build

      # --- Pages ブランチへ直接push ---
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token:   ${{ secrets.GH_PAGES_TOKEN }}
          publish_branch: gh-pages
          publish_dir:    ./dist
          # optional: コミット作者情報
          commit_user_name:  github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
